## Spring Boot application configuration file
---
spring:
    data:
        rest:
            detection-strategy: annotated
            base-path: /api
            default-page-size: 20
            max-page-size: 50
            page-param-name: p
            limit-param-name: l
            sort-param-name: s
            return-body-on-create: true
            return-body-on-update: false
    h2:
        console:
            enabled: true
    sql:
        init:
            platform: h2
    datasource:
        url: jdbc:h2:mem:DEV_DB
        driver-class-name: org.h2.Driver
        username: sa
        password:
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        show-sql: false
        hibernate:
            ddl-auto: create-drop
