---
apiVersion: v1
kind: Namespace
metadata:
  name: devops


---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: container-registry
  namespace: devops
automountServiceAccountToken: false


---
apiVersion: v1
kind: Service
metadata:
  namespace: devops
  name: container-registry
  labels:
    app: container-registry
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 31050
  selector:
    app: container-registry
  type: NodePort


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: devops
  name: container-registry-pvc
spec:
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 512Mi
    limits:
      storage: 5Gi


---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: devops
  name: container-registry-deployment
  labels:
    app: container-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container-registry
  template:
    metadata:
      namespace: devops
      labels:
        app: container-registry
    spec:
      serviceAccountName: container-registry
      volumes:
        - name: container-registry-storage
          persistentVolumeClaim:
            claimName: container-registry-pvc
      containers:
        - name: registry
          image: registry:2.8.3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
              protocol: TCP
          resources:
            requests:
              cpu: "100m"
              memory: "192Mi"
              ephemeral-storage: "256Mi"
            limits:
              memory: "256Mi"
              ephemeral-storage: "1Gi"
          volumeMounts:
            - mountPath: "/var/lib/registry"
              name: container-registry-storage
